M48
; DRILL file {KiCad 8.0.5} date 2024-10-24T17:50:14+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-24T17:50:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.397
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X191.245Y-57.751
X191.245Y-67.753
T2
X188.34Y-87.435
X188.34Y-92.285
T3
X191.37Y-87.135
X191.37Y-92.585
T4
X103.5Y-55.5
X103.5Y-145.5
X169.5Y-55.5
X169.5Y-145.5
M30
