M48
; DRILL file {KiCad 8.0.6} date 2024-11-26T08:02:46+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-26T08:02:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X203.24Y-82.885
X203.24Y-87.735
T2
X206.27Y-82.585
X206.27Y-88.035
T3
X143.5Y-44.5
X143.5Y-134.5
X189.5Y-44.5
X189.5Y-134.5
M30
